// <auto-generated />
using FermViewApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FermViewApi.Migrations
{
    [DbContext(typeof(TemperatureDataContext))]
    [Migration("20190121043624_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FermViewApi.Models.TemperatureData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BrewName");

                    b.Property<decimal>("Temperature");

                    b.Property<DateTime>("Time");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("TemperatureData");
                });
#pragma warning restore 612, 618
        }
    }
}
